import './globals.css'

import type { Metadata } from 'next'
import React from 'react'

import Navbar from '../../lib/components/Navbar/Navbar'

export const metadata: Metadata = {
  title: 'Notion Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className="container">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
